// Plain-language explanations for every bit of jargon the UI shows. Used by <Term k="...">.
export const GLOSSARY: Record<string, [string, string]> = {
  ema: ['EMA (exponential moving average)', 'The average price over the last N bars, weighting recent bars more. Price above a rising EMA = uptrend. EMA50/EMA200 are the slow "big trend" lines.'],
  rsi: ['RSI (relative strength index)', 'Momentum from 0 to 100. Above 70 = stretched up (overbought), below 30 = stretched down (oversold). Strong trends can stay stretched for a long time.'],
  macd: ['MACD', 'Difference between a fast and a slow EMA. Histogram above zero = momentum pointing up.'],
  atr: ['ATR (average true range)', 'Typical size of one bar\'s move. Useful for placing stops: a stop closer than ~1 ATR gets hit by noise.'],
  bollinger: ['Bollinger bands', 'A band two standard deviations around the 20-bar average. Narrow bands = calm market; a "squeeze" is the narrowest in months.'],
  funding: ['Funding rate', 'What perpetual-futures longs pay shorts (or vice versa) every 8h. High positive = crowded longs paying up; negative = shorts paying. Extremes often precede flushes.'],
  oi: ['Open interest (OI)', 'Total value of open futures positions. Rising OI = new leverage entering. It measures leverage, not buying or selling.'],
  ls: ['Long/short ratio', 'Accounts long vs short on Binance futures. Retail crowding is a contrarian warning, not a signal on its own.'],
  taker: ['Taker buy/sell', 'Volume from traders who hit the market immediately. Above 1 = aggressive buyers dominate.'],
  mindshare: ['Mindshare', 'Share of all tracked mentions that talk about this asset. Measures attention, not direction.'],
  velocity: ['Mention velocity', 'Mentions in the last 4h vs the 24h pace. 2x = attention doubling.'],
  xmentions: ['X mentions (Elfa)', 'Posts on X mentioning the ticker in 24h, from Elfa, with the change vs the prior 24h. Attention only: it says nothing about whether people are bullish.'],
  score: ['Rook score', 'Explainable composite from -100 to +100: daily, 4h and 1h trend, momentum, news tone and positioning. It is a summary of the evidence, not a forecast.'],
  pup: ['P(up)', 'Model probability that the price is higher after the horizon. 50% = coin flip. It is shrunk toward the base rate until the model proves skill on graded forecasts.'],
  base: ['Base rate', 'How often price was higher over this horizon historically, with no model at all. Any forecast has to beat this.'],
  edge: ['Edge', 'Whether the model beats the base rate on out-of-sample or live graded forecasts. "No edge" is common and honest.'],
  brier: ['Brier score', 'Squared error of probability forecasts (lower is better). Skill = how much lower than the base rate\'s Brier.'],
  cone: ['Forecast cone', 'Where price should land 80% of the time (10th-90th percentile), from volatility-scaled historical moves. Its hit rate is graded and the width self-corrects toward 80%.'],
  coverage: ['Cone hit-rate', 'How often the realised price landed inside the 10-90% cone. Target 80%. Lower = cone too narrow, higher = too wide.'],
  setup: ['Setup', 'A recognisable chart pattern. Each shows how often it worked historically on this asset vs the base rate; "no clear edge" means it did not beat chance.'],
  levels: ['Support / resistance', 'Prices where swings reversed before (clustered pivot highs/lows). More touches = more significant.'],
  dvol: ['DVOL', 'Deribit\'s implied-volatility index for BTC options: the market\'s expected annualised volatility.'],
  fng: ['Fear & Greed', 'Crowd-mood index 0-100. Extremes are contrarian context, not triggers.'],
  liq: ['Liquidations', 'Leveraged positions force-closed by the exchange. Long liquidations accelerate drops; short liquidations accelerate rallies.'],
  fdv: ['FDV (fully diluted valuation)', 'Price times the maximum supply. A low market-cap/FDV ratio means lots of future unlocks (sell pressure).'],
  tvl: ['TVL', 'Total value locked in a DeFi protocol or chain.'],
  vol: ['Volatility', 'Annualised standard deviation of daily returns. 60% means a typical year swings about ±60%.'],
  dd: ['Max drawdown', 'Largest peak-to-trough drop over the period.'],
  riskshare: ['Risk share', 'Each position\'s contribution to the portfolio\'s total variance. One asset at 70% risk share = the portfolio mostly IS that asset.'],
  corr: ['Correlation', '+1 = move together, 0 = unrelated, -1 = opposite. Highly correlated holdings do not diversify.'],
  early: ['Early (lead-time)', 'Elfa\'s lead-time play: a contract trending on Telegram but not yet on X. Telegram tends to lead. Extremely high risk.'],
  verified: ['Verified token', 'On Jupiter\'s verified list. Unverified tokens are mostly airdropped spam or copies and are excluded from totals.'],
  cdi: ['CDI', 'Brazil\'s interbank rate, which tracks the Selic. Most fixed income and savings in BRL pay a % of CDI, so it is the hurdle any BRL investment has to beat.'],
  xcdi: ['Return vs CDI', 'Return in BRL minus what CDI paid over the same window (as an excess return). Negative = you would have done better in a CDI fund, without the risk.'],
  selic: ['Selic', 'Brazil\'s policy interest rate, set by the central bank (Copom) roughly every 45 days.'],
  ipca: ['IPCA', 'Brazil\'s official consumer inflation index (IBGE). The 12-month figure compounds the last 12 monthly readings.'],
  real_rate: ['Real interest rate', 'Interest rate minus inflation: what savings actually earn in purchasing power. Brazil\'s is among the highest in the world.'],
  pos52: ['52-week range', 'Where the price sits between its lowest and highest level of the past year. Left = near the yearly low, right = near the high.'],
  trend: ['Trend (daily)', 'Up = price above a rising 50-day average that is above the 200-day average. Down = the opposite. Mixed = they disagree.'],
  bp: ['Basis point (bp)', 'One hundredth of a percentage point. A yield moving from 4.00% to 4.25% is +25 bp.'],
  latency: ['Latency', 'Time from the exchange event to your screen. The app measures every source and uses the fastest healthy one first.'],
}
